# Change these first
owner: mbuechner # Your GitHub organization or username, where this repository lives
repo: ddbstatus # The name of this repository

sites:
  - name: "https://www.archivportal-d.de (Subportal „Archivportal-D“)"
    url: https://www.archivportal-d.de
  - name: "https://download.codingdavinci.de (Filesharing von Coding da Vinci)"
    url: https://download.codingdavinci.de
  - name: "https://report.codingdavinci.de (Webanalytik von Coding da Vinci)"
    url: https://report.codingdavinci.de
  - name: "https://codingdavinci.de (Coding da Vinci)"
    url: https://codingdavinci.de
  - name: "https://hub.culturegraph.org/entityfacts/118540238 (Datendienst „Entity Facts“)"
    url: https://hub.culturegraph.org/entityfacts/118540238
  - name: "https://api.deutsche-digitale-bibliothek.de (API )"
    url: https://api.deutsche-digitale-bibliothek.de
  - name: "https://ausstellungen.deutsche-digitale-bibliothek.de/regen/ (Virtuelle Ausstellungen )"
    url: https://ausstellungen.deutsche-digitale-bibliothek.de/regen/
  - name: "https://ausstellungen-red.deutsche-digitale-bibliothek.de/ (Redaktionssystem der Virtuellen Ausstellungen)"
    url: https://ausstellungen-red.deutsche-digitale-bibliothek.de/
    expectedStatusCodes:
      - 401
  - name: "https://ccc.deutsche-digitale-bibliothek.de (Subportal „Sammlungsgut aus kolonialen Kontexten“)"
    url: https://ccc.deutsche-digitale-bibliothek.de
  - name: "https://cms.deutsche-digitale-bibliothek.de (Content Management System)"
    url: https://cms.deutsche-digitale-bibliothek.de
  - name: "https://datashare.deutsche-digitale-bibliothek.de/ (Datashare)"
    url: https://datashare.deutsche-digitale-bibliothek.de/
  - name: "https://go.deutsche-digitale-bibliothek.de (DDBgo)"
    url: https://go.deutsche-digitale-bibliothek.de
  - name: "https://iiif.deutsche-digitale-bibliothek.de/image/2/01610200-7559-47e9-8f7c-bd4323cbd794/full/full/0/default.jpg (IIIF-Service )"
    url: https://iiif.deutsche-digitale-bibliothek.de/image/2/01610200-7559-47e9-8f7c-bd4323cbd794/full/full/0/default.jpg
  - name: "https://jira.deutsche-digitale-bibliothek.de (Jira)"
    url: https://jira.deutsche-digitale-bibliothek.de
  - name: "https://labs.deutsche-digitale-bibliothek.de/app/beagen (DDBlabs: Beagen)"
    url: https://labs.deutsche-digitale-bibliothek.de/app/beagen
  - name: "https://labs.deutsche-digitale-bibliothek.de/app/ddbapi (DDBlabs: DDBapi)"
    url: https://labs.deutsche-digitale-bibliothek.de/app/ddbapi
  - name: "https://labs.deutsche-digitale-bibliothek.de/app/ddbid (DDBlabs: DDBid)"
    url: https://labs.deutsche-digitale-bibliothek.de/app/ddbid
  - name: "https://labs.deutsche-digitale-bibliothek.de/app/ddbidgen (DDBlabs: DDBIdGen)"
    url: https://labs.deutsche-digitale-bibliothek.de/app/ddbidgen
  - name: "https://labs.deutsche-digitale-bibliothek.de/app/ddbmeme (DDBlabs: DDBmeme)"
    url: https://labs.deutsche-digitale-bibliothek.de/app/ddbmeme
  - name: "https://labs.deutsche-digitale-bibliothek.de/app/ef2so/118540238 (DDBlabs: EF2SO)"
    url: https://labs.deutsche-digitale-bibliothek.de/app/ef2so/118540238
  - name: "https://labs.deutsche-digitale-bibliothek.de/iiif/presentation/3 (DDBlabs: IIIF)"
    url: https://labs.deutsche-digitale-bibliothek.de/iiif/presentation/3
  - name: "https://labs.deutsche-digitale-bibliothek.de/app/iiif-presentation (DDBlabs: IIIF Presentation)"
    url: https://labs.deutsche-digitale-bibliothek.de/app/iiif-presentation
  - name: "https://labs.deutsche-digitale-bibliothek.de/app/zdbdump (DDBlabs: ZDBdump)"
    url: https://labs.deutsche-digitale-bibliothek.de/app/zdbdump
  - name: "https://maps.deutsche-digitale-bibliothek.de/ (Kartenserver)"
    url: https://maps.deutsche-digitale-bibliothek.de/
  - name: "https://mint.deutsche-digitale-bibliothek.de (DDBmint)"
    url: https://mint.deutsche-digitale-bibliothek.de
    expectedStatusCodes:
      - 401
  - name: "https://mqa.deutsche-digitale-bibliothek.de (Metadata Quality Assessment)"
    url: https://mqa.deutsche-digitale-bibliothek.de
    expectedStatusCodes:
      - 401
  - name: "https://oai.deutsche-digitale-bibliothek.de (DDBoai)"
    url: https://oai.deutsche-digitale-bibliothek.de
  - name: "https://pro.deutsche-digitale-bibliothek.de (DDBpro)"
    url: https://pro.deutsche-digitale-bibliothek.de
  - name: "https://registrierung.deutsche-digitale-bibliothek.de (Registrierung)"
    url: https://registrierung.deutsche-digitale-bibliothek.de
  - name: "https://report.deutsche-digitale-bibliothek.de/ (Webanalytik)"
    url: https://report.deutsche-digitale-bibliothek.de/
  - name: "https://viewer.deutsche-digitale-bibliothek.de/ (DDBviewer)"
    url: https://viewer.deutsche-digitale-bibliothek.de/
  - name: "https://viewer-dzp.deutsche-digitale-bibliothek.de (DDBviewer fürs Zeitungsportal)"
    url: https://viewer-dzp.deutsche-digitale-bibliothek.de
  - name: "https://webmail.deutsche-digitale-bibliothek.de/ (DDBwebmail)"
    url: https://webmail.deutsche-digitale-bibliothek.de/
  - name: "https://wiki.deutsche-digitale-bibliothek.de (Wiki)"
    url: https://wiki.deutsche-digitale-bibliothek.de
  - name: "https://www.deutsche-digitale-bibliothek.de (Deutsche Digitale Bibliothek)"
    url: https://www.deutsche-digitale-bibliothek.de
  - name: "https://www.deutsche-digitale-bibliothek.de/newspaper (Zeitungsportal)"
    url: https://www.deutsche-digitale-bibliothek.de/newspaper
  - name: "https://www.deutsche-digitale-bibliothek.de/item/TNPFDKO2VDGBZ72RWC6RKDNZYZQZP3XK (Deutsche Digitale Bibliothek: Objektseite)"
    url: https://www.deutsche-digitale-bibliothek.de/item/TNPFDKO2VDGBZ72RWC6RKDNZYZQZP3XK
  - name: "https://www.deutsche-digitale-bibliothek.de/person/gnd/118540238 (Deutsche Digitale Bibliothek: Personenseite)"
    url: https://www.deutsche-digitale-bibliothek.de/person/gnd/118540238
  - name: "https://www.deutsche-digitale-bibliothek.de/organization/YNKIAG7DFC4HZOATBPG75IFEY5BUDYUS (Deutsche Digitale Bibliothek: Organisationenseite)"
    url: https://www.deutsche-digitale-bibliothek.de/organization/YNKIAG7DFC4HZOATBPG75IFEY5BUDYUS
  - name: "https://www.deutsche-digitale-bibliothek.de/organization/gnd/2024343-1 (Deutsche Digitale Bibliothek: Organisationenseite (GND))"
    url: https://www.deutsche-digitale-bibliothek.de/organization/gnd/2024343-1
  - name: "https://www.deutsche-digitale-bibliothek.de/content/blog/was-fuer-ein-abend-was-fuer-ein-fest-wir-sagen-danke (Deutsche Digitale Bibliothek: Content)"
    url: https://www.deutsche-digitale-bibliothek.de/content/blog/was-fuer-ein-abend-was-fuer-ein-fest-wir-sagen-danke
  - name: "http://xtree.digicult-verbund.de/ (xTree)"
    url: http://xtree.digicult-verbund.de/
  - name: "https://wiki.dnb.de (Wiki (DNB))"
    url: https://wiki.dnb.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ddbstatus
  logoUrl: https://raw.githubusercontent.com/Deutsche-Digitale-Bibliothek/ddbpro/master/web/themes/custom/ddbp/src/images/logo-ddbpro.svg
  favicon: https://raw.githubusercontent.com/Deutsche-Digitale-Bibliothek/ddbpro/master/web/themes/custom/ddbp/favicon.ico
  faviconSvg: https://raw.githubusercontent.com/Deutsche-Digitale-Bibliothek/ddbpro/master/web/themes/custom/ddbp/src/images/logo-signet-main.svg
  name: DDBstatus
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /ddbstatus
    - title: GitHub
      href: https://github.com/mbuchner/ddbstatus

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Aktive Vorfälle
  allSystemsOperational: Alle Systeme sind verfügbar
  incidentReport: "Bericht des Vorfalls #$NUMBER →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS Beitrag
  incidentTitle: Details des Vorfall $NUMBER
  incidentDetails: Details des Vorfalls
  incidentFixed: Gelöst
  incidentOngoing: Offen
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentViewOnGitHub: Ansehen und Abonnieren auf GitHub
  incidentCommentSummary: Geschrieben am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Vorfällen
  pastIncidents: Frühere Vorfällen
  pastIncidentsResolved: Gelöst in $MINUTES Minuten mit $POSTS Beiträgen
  liveStatus: Live Status
  overallUptime: "Verfügbarkeit: $UPTIME"
  overallUptimeTitle: Verfügbarkeit
  averageResponseTime: "Durchschnittliche Reaktionszeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Reaktionszeit
  sevelDayResponseTime: Reaktionszeit der letzten 7 Tage
  responseTimeMs: Reaktionszeit (ms)
  up: Hoch
  down: Niedrig
  degraded: Verschlechtert
  ms: ms
  loading: Laden
  navGitHub: GitHub
  footer: ""
  rateLimitExceededTitle: Anzahl der Zugriffe überschritten
  rateLimitExceededIntro: Sie haben die Anzahl der Anfragen, die Sie in einer Stunde durchführen können, überschritten. Sie müssen warten, bevor Sie diese Website erneut aufrufen können. Alternativ können Sie ein persönliches GitHub-Zugangs-Token hinzufügen, um diese Website weiterhin zu nutzen.
  rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
  rateLimitExceededErrorMeaning: Diese Website verwendet die GitHub-API, um Echtzeitdaten über den Status der Websiten abzurufen. Standardmäßig erlaubt GitHub jeder IP-Adresse 60 Anfragen pro Stunde. Diese haben Sie verbraucht.
  rateLimitExceededErrorHowCanFix: Was kann ich tun?
  rateLimitExceededErrorFix: Sie können eine Stunde warten bis das Limit für Ihre IP-Adresse wiederhergestellt wird. Alternativ können Sie Ihr persönliches GitHub-Zugangs-Token hinzufügen, mit dem Sie zusätzliche 5.000 Anfragen pro Stunde erhalten.
  rateLimitExceededGeneratePAT: Wie erstelle ich einen persönlichen Zugangstoken?
  rateLimitExceededHasSet: Sie haben ein persönliches Zugangstoken gesetzt.
  rateLimitExceededRemoveToken: Zugangstoken entfernen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Kopieren und Einfügen des Tokens
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Es ist ein Fehler aufgetreten
  errorIntro: Beim Versuch, die neuesten Statusinformationen zu erhalten, ist ein Fehler aufgetreten.
  errorText: Bitte versuchen Sie es in wenigen Augenblicken erneut.
  errorHome: Zur Homepage gehen
  pastScheduledMaintenance: Vergangene planmäßige Wartung
  scheduledMaintenance: Planmäßige Wartung
  scheduledMaintenanceSummaryStarted: Begonnen am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für $DURATION Minuten
  startedAt: Angefangen am
  startsAt: Fängt an am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Abgeschlossen
  incidentScheduled: Geplant
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: Alles
