# Change these first
owner: mbuechner # Your GitHub organization or username, where this repository lives
repo: ddbstatus # The name of this repository

sites:
  - name: Deutsche Digitale Bibliothek (https://www.deutsche-digitale-bibliothek.de)
    url: https://www.deutsche-digitale-bibliothek.de
  - name: DDBpro (https://pro.deutsche-digitale-bibliothek.de)
    url: https://pro.deutsche-digitale-bibliothek.de
  - name: DDBgo (https://go.deutsche-digitale-bibliothek.de)
    url: https://go.deutsche-digitale-bibliothek.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ddbstatus
  logoUrl: https://raw.githubusercontent.com/Deutsche-Digitale-Bibliothek/ddbpro/master/web/themes/custom/ddbp/src/images/logo-ddbpro.svg
  favicon: https://raw.githubusercontent.com/Deutsche-Digitale-Bibliothek/ddbpro/master/web/themes/custom/ddbp/favicon.ico
  faviconSvg: https://raw.githubusercontent.com/Deutsche-Digitale-Bibliothek/ddbpro/master/web/themes/custom/ddbp/src/images/logo-signet-main.svg
  name: DDBstatus
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /ddbstatus
    - title: GitHub
      href: https://github.com/mbuchner/ddbstatus

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Aktive Zwischenfälle
  allSystemsOperational: Alle Systeme sind verfügbar
  incidentReport: "Bericht des Zwischenfalls #$NUMBER →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS posts
  incidentTitle: Details des Zwischenfall $NUMBER
  incidentDetails: Zwischenfalldetails
  incidentFixed: Gelöst
  incidentOngoing: Offen
  incidentOpenedAt: Geöffnet am
  incidentClosedAt: Geschlossen am
  incidentViewOnGitHub: Ansehen und Abonnieren auf GitHub
  incidentCommentSummary: Geschrieben am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Zwischenfällen
  pastIncidents: Frühere Zwischenfällen
  pastIncidentsResolved: Gelöst in $MINUTES Minuten mit $POSTS posts
  liveStatus: Live Status
  overallUptime: "Verfügbarkeit: $UPTIME"
  overallUptimeTitle: Verfügbarkeit
  averageResponseTime: "Durchschnittliche Reaktionszeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Reaktionszeit
  sevelDayResponseTime: Reaktionszeit der letzten 7 Tage
  responseTimeMs: Reaktionszeit (ms)
  up: Hoch
  down: Runter
  degraded: Degradiert
  ms: ms
  loading: Laden
  navGitHub: GitHub
  footer: 
  rateLimitExceededTitle: Rate limit überschritten
  rateLimitExceededIntro: Sie haben die Anzahl der Anfragen, die Sie in einer Stunde durchführen können, überschritten. Sie müssen warten, bevor Sie diese Website erneut aufrufen können. Alternativ können Sie ein persönliches GitHub-Zugangs-Token hinzufügen, um diese Website weiterhin zu nutzen.
  rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
  rateLimitExceededErrorMeaning: Diese Website verwendet die GitHub-API, um Echtzeitdaten über den Status unserer Websites abzurufen. Standardmäßig erlaubt GitHub jeder IP-Adresse 60 Anfragen pro Stunde, die Sie verbraucht haben.
  rateLimitExceededErrorHowCanFix: Wie kann ich das reparieren?
  rateLimitExceededErrorFix: Sie können eine weitere Stunde warten und das Limit für Ihre IP-Adresse wird wiederhergestellt. Alternativ können Sie Ihr persönliches GitHub-Zugangs-Token hinzufügen, mit dem Sie zusätzliche 5.000 Anfragen pro Stunde erhalten.
  rateLimitExceededGeneratePAT: Erfahren Sie, wie Sie ein persönliches Zugangstoken erstellen
  rateLimitExceededHasSet: Sie haben ein persönliches Zugangstoken gesetzt.
  rateLimitExceededRemoveToken: Zugangstoken entfernen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Kopieren und Einfügen des Tokens
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Es ist ein Fehler aufgetreten
  errorIntro: Beim Versuch, die neuesten Statusinformationen zu erhalten, ist ein Fehler aufgetreten.
  errorText: Sie können es in wenigen Augenblicken erneut versuchen.
  errorHome: Zur Homepage gehen
  pastScheduledMaintenance: Vergangene planmäßige Wartung
  scheduledMaintenance: Planmäßige Wartung
  scheduledMaintenanceSummaryStarted: Begonnen am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für $DURATION Minuten
  startedAt: Angefangen am
  startsAt: Fängt an am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Abgeschlossen
  incidentScheduled: Geplant
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1y
  durationAll: Alles
